# Generated by Django 4.2.5 on 2024-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_site', '0002_latest_remove_album_youtube_video_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest',
            name='link',
            field=models.TextField(default='', verbose_name='paste youtube video embed code'),
        ),
    ]
