# Generated by Django 4.2.13 on 2024-05-12 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_site', '0003_alter_latest_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist',
            field=models.TextField(default='', verbose_name='paste embed code for youtube playlist'),
        ),
        migrations.CreateModel(
            name='AlbumSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='', null=True, verbose_name='about the song')),
                ('link', models.TextField(default='', verbose_name='Paste Embed code here')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_site.album')),
            ],
            options={
                'verbose_name': 'Album Songs',
            },
        ),
    ]
