# Generated by Django 4.2.11 on 2024-05-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_site', '0004_alter_playlist_playlist_albumsongs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest',
            name='link',
            field=models.TextField(default='', verbose_name='Paste Embed code of latest Video'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist',
            field=models.CharField(default='', max_length=1000, verbose_name='paste embed code for youtube playlist'),
        ),
        migrations.DeleteModel(
            name='AlbumSongs',
        ),
    ]
