# Generated by Django 4.2.11 on 2024-05-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_site', '0006_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery'},
        ),
    ]
